export default function Zigzag() {
  return (
    <section>
      <div className="max-w-6xl mx-auto px-4 sm:px-6">
        <div className="py-12 md:py-20 border-t border-gray-800">
          {/* Section header */}
          <div className="max-w-3xl mx-auto text-center pb-12 md:pb-16">
            <h1 className="h2 mb-4">
              Quiénes
              somos?
            </h1>
          </div>

          {/* Items */}
          <div className="grid gap-20">
            {/* 1st item */}
            <div className="md:grid md:grid-cols-12 md:gap-6 items-center">
              {/* Content */}
              <div
                className="max-w-xl md:max-w-none md:w-full mx-auto col-span-12"
                data-aos="fade-right"
              >
                <div className="md:pr-4 lg:pr-12 xl:pr-16">
                  <p className="text-xl text-gray-400 mb-4">
                    Estamos
                    orgullosos
                    de
                    presentarle
                    un
                    sitio
                    de
                    juegos
                    donde
                    hay
                    algo
                    paca
                    todos,
                    desde
                    juegos
                    de
                    mesa
                    clásiros
                    hasta
                    las
                    ditimas
                    innovaciones
                    en
                    el
                    mundo
                    de
                    los
                    videojuegos.
                    Nuestra
                    misión
                    es
                    reunir
                    a
                    jugadores
                    de
                    todo
                    el
                    mundo
                    afreciendo
                    una.
                    amplia
                    gama
                    de
                    juegos
                    que
                    Inspiren,
                    entretengan
                    y
                    eduquen.
                    En
                    Reyfortuna,
                    creemos
                    que
                    los
                    Juegos
                    son
                    más
                    que
                    solo
                    diversion.
                    son
                    una.
                    herramienta
                    poderosa
                    para
                    la
                    socialización,
                    el
                    aprendiraje
                    y
                    el
                    crecimiento
                    personal.
                    Por
                    lo
                    tanto,
                    seleccionamos
                    cuidadosamente
                    cada
                    juego
                    para
                    asegurarnos
                    de
                    que
                    cumpla
                    con
                    nuestros
                    altos
                    estándares
                    de
                    calidad
                    y
                    variedad.
                    Nuestro
                    equipo
                    de
                    expertos
                    investiga
                    constantemente
                    el
                    mertado
                    de
                    los
                    juegos
                    para
                    traer
                    los
                    juegos
                    más
                    innovadores
                    y
                    emocionantes
                    a
                    nuestras
                    vidas:
                    También
                    estamos
                    orgullosos
                    de
                    nuestra
                    comunidad,
                    que
                    ayuda
                    a
                    dar
                    forma
                    a
                    nuestra
                    visión,
                    comparte
                    comentarios
                    y
                    parucipa
                    en
                    la
                    creación
                    de
                    experiencias
                    de
                    juego
                    unicas.
                    Gracias
                    por
                    elegir
                    Regfartuna.
                    Prometemos
                    seguir
                    ofreciéndote
                    nuevos
                    juegos
                    y
                    caracteristicas
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
